experiment: orderless_levelset
ol:
  epsilon: 1e-3
  mu: 1e-4
  nu: 1e-4
  lambda1: 1.5
preprocessing:
  sigma: 1
postprocessing:
  sigma: 50

hydra:
  run:
    dir: ./data/cell-detection/exp/${now:%Y-%m-%d_%H:%M:%S}
  sweep:
    dir: ./data/cell-detection/exp/${now:%Y-%m-%d_%H:%M:%S}
    subdir: ${hydra.job.num}
