experiment: orderless_levelset
ol:
  epsilon: 1e-2
  mu: 1e-3
  nu: 1e-6
  lambda1: 1
preprocessing:
  sigma: 0
postprocessing:
  sigma: 0
image:
  path: cell-detection/raw/cropped_first_third.h5
  equalize: local
  regenerate: False
  unsharp_mask:
    amount: 3
    radius: 80
  l0_smoothing:
    lambda_: 0.01
    kappa: 3.0
  q_lower_bound: 0
  slice:
    x:
      - 360
      - 370
    y:
      - 50
      - -50
    z:
      - 50
      - -50

hydra:
  job:
    chdir: True
  run:
    dir: ./data/cell-detection/exp/${now:%Y-%m-%d_%H:%M:%S}
  sweep:
    dir: ./data/cell-detection/exp/${now:%Y-%m-%d_%H:%M:%S}
    subdir: ${hydra.job.num}
