experiment: orderless_levelset
ol:
  epsilon: 1e-2
  mu: 1e-5
  nu: 1e-3
  lambda1: 1.1
preprocessing:
  sigma: 0.1
postprocessing:
  sigma: 0.5
image:
  path: cell-detection/raw/cropped_first_third.h5
  equalize: local
  regenerate: False
  unsharp_mask:
    amount: 3
    radius: 80
  lower_bound: 0
  slice:
    x:
      - 300
      - 400
    y:
      - 0
      - -1
    z:
      - 0
      - -1

hydra:
  job:
    chdir: True
  run:
    dir: ./data/cell-detection/exp/${now:%Y-%m-%d_%H:%M:%S}
  sweep:
    dir: ./data/cell-detection/exp/${now:%Y-%m-%d_%H:%M:%S}
    subdir: ${hydra.job.num}
