experiment: orderless_levelset
ol:
  epsilon: 1e-2
  mu: 1e-5
  nu: 1e-4
  lambda1: 1.1
preprocessing:
  sigma: 0.1
postprocessing:
  sigma: 0.5
image:
  path: cell-detection/raw/cropped_first_third.h5
  equalize: local
  slice:
    x: 356
    y: None
    z: None

hydra:
  job:
    chdir: True
  run:
    dir: ./data/cell-detection/exp/${now:%Y-%m-%d_%H:%M:%S}
  sweep:
    dir: ./data/cell-detection/exp/${now:%Y-%m-%d_%H:%M:%S}
    subdir: ${hydra.job.num}
